- name: Instalar Docker y construir imagen Hadoop
  hosts: hadoop
  become: true

  tasks:

    - name: Instalar dependencias básicas
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        update_cache: true

    - name: Añadir GPG key de Docker
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Añadir repositorio Docker
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        state: present

    - name: Instalar Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        update_cache: true
    - name: Construir imagen Hadoop
      command: "docker run -d   --name=wireguard   --cap-add=NET_ADMIN   --cap-add=SYS_MODULE `#optional`   -e PUID=1000   -e PGID=1000   -e TZ=Etc/UTC   -e SERVERURL=wireguard.domain.com `#optional`   -e SERVERPORT=51820 `#optional`   -e PEERS=1 `#optional`   -e PEERDNS=auto `#optional`   -e INTERNAL_SUBNET=10.13.13.0 `#optional`   -e ALLOWEDIPS=0.0.0.0/0 `#optional`   -e PERSISTENTKEEPALIVE_PEERS= `#optional`   -e LOG_CONFS=true `#optional`   -p 51820:51820/udp   -v /path/to/wireguard/config:/config   -v /lib/modules:/lib/modules `#optional`   --sysctl="net.ipv4.conf.all.src_valid_mark=1"   --restart unless-stopped   lscr.io/linuxserver/wireguard:latest"

        #    - name: Lanzar contenedor Hadoop
        #      docker_container:
        #        name: hadoop
        #        image: hadoop-img
        #        state: started
        #        restart_policy: always
        #        ports:
        #          - "9870:9870"
        #        volumes:
        #          - /home/hadoop/data:/home/hadoop/data  # Si quieres persistencia, opcional
