- name: Download Zabbix release package
  become: yes
  ansible.builtin.get_url:
    url: https://repo.zabbix.com/zabbix/7.0/debian/pool/main/z/zabbix-release/zabbix-release_7.0-1+debian12_all.deb
    dest: /tmp/zabbix-release_7.0-1+debian12_all.deb

- name: Install Zabbix release package
  become: yes
  ansible.builtin.apt:
    deb: /tmp/zabbix-release_7.0-1+debian12_all.deb
    update_cache: yes

- name: Update apt repository cache
  become: yes
  ansible.builtin.apt:
    update_cache: yes

- name: Install Zabbix agent
  become: yes
  ansible.builtin.apt:
    name: zabbix-agent
    state: present

- name: Copy Zabbix agent configuration file
  become: yes
  ansible.builtin.copy:
    src: ../files/zabbix_agentd.conf
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: root
    mode: '0644'

- name: Restart Zabbix agent service
  become: yes
  ansible.builtin.systemd:
    name: zabbix-agent
    state: restarted
    enabled: yes