- name: Crear contenedor MongoDB con replicación y keyFile
  community.docker.docker_container:
    name: mongodb-slave
    image: mongo:latest
    detach: true
    hostname: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - /tmp/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - /tmp/mongo-keyfile:/data/configdb/mongo-keyfile
    env:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    command: --replSet myReplicaSet --keyFile /data/configdb/mongo-keyfile --bind_ip_all
