- name: Crear directorio de la app Docker
  file:
    path: /opt/kafka-docker
    state: directory
    mode: "0755"

- name: Descargar imagen de ZooKeeper
  community.docker.docker_image:
    name: zookeeper
    tag: "3.8"
    source: pull

- name: Ejecutar contenedor ZooKeeper
  community.docker.docker_container:
    name: zookeeper
    image: zookeeper:3.8
    ports:
      - "2181:2181"
    restart_policy: always

- name: Descargar imagen de Kafka (Bitnami)
  community.docker.docker_image:
    name: bitnami/kafka
    tag: "3.6.1"
    source: pull

- name: Ejecutar contenedor Kafka (Bitnami)
  community.docker.docker_container:
    name: kafka
    image: bitnami/kafka:3.6.1
    ports:
      - "9092:9092"
    env:
      KAFKA_ZOOKEEPER_CONNECT: "10.0.20.40:2181"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://10.0.20.40:9092"
    restart_policy: always
    state: started

- name: Esperar a que Kafka esté disponible en el puerto 9092
  wait_for:
    host: 127.0.0.1
    port: 9092
    delay: 5
    timeout: 60

- name: Crear topic Kafka "stream_zona1"
  command: >
    docker exec kafka kafka-topics.sh
    --create
    --bootstrap-server localhost:9092
    --replication-factor 1
    --partitions 1
    --topic stream_zona1
  register: create_topic_output
  failed_when: "'already exists' not in create_topic_output.stderr and create_topic_output.rc != 0"

- name: Instalar JDK, Maven y Git en el LXC
  apt:
    name:
      - openjdk-17-jdk
      - maven
      - git
    state: present
    update_cache: yes

- name: Crear directorio del proyecto Java
  file:
    path: /opt/Sistema-Konkurrente-eta-banatuak
    state: directory
    mode: "0755"

- name: Clonar repositorio del proyecto Java
  git:
    repo: https://github.com/PBL6-URTEGI/Sistema-Konkurrente-eta-banatuak.git
    dest: /opt/Sistema-Konkurrente-eta-banatuak
    version: main
    force: yes
